#
# To deploy:
#
# kubectl apply -f scripts/deploy.yaml
#
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers: 
      - name: metadata
        image: $CONTAINER_REGISTRY/metadata:$VERSION
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "4000"
        - name: DBHOST
          value: mongodb://mongodb:27017
        - name: DBNAME
          value: metadata
        - name: RABBIT
          value: amqp://test:test@rabbit:5672
        - name: STORAGE_ACCOUNT_NAME
          value: ${STORAGE_ACCOUNT_NAME}
        - name: STORAGE_ACCESS_KEY
          value: ${STORAGE_ACCESS_KEY}
---
apiVersion: v1
kind: Service
metadata:
  name: metadata
spec:
  selector:
    app: metadata
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
